/* ═══ Drafts — five-star reads waiting for their write-up ═══
   Generated by scripts/sync-goodreads.py when you rate a book
   5 stars on Goodreads. This file is NOT loaded by the site —
   nothing here is public until you move it into js/books.js.

   To publish one: fill in section ("Fiction" or "Nonfiction"),
   tag/tagLabel (the filter chip), and short (your take), then
   cut the block and paste it into the BOOKS list in js/books.js
   wherever you want it to appear. Add a "full" list of
   paragraphs if you want the Full-review toggle.

   Don't want a book on the shelf at all? Delete its block AND
   add its title to DRAFT_SKIP below so the sync doesn't draft
   it again. */

window.DRAFT_SKIP = [
];

window.DRAFTS = [
];
