/* ============================================================
   HEART'S LIBRARY — page renderers.
   One small file drives the photography pages (the wall at
   index.html, gallery.html) and the
   background wings (pins, games, writing), reading the plain
   data files. Each block no-ops unless its container exists,
   so every page can load the same script. You never need to
   edit this file to post — edit the data files.
   ============================================================ */
(function () {
  "use strict";

  function esc(s) {
    return String(s == null ? "" : s)
      .replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;");
  }
  var TRIPS = window.TRIPS || [];
  /* Most collections are logged before their photographs exist — the
     list goes back to 2019 and the camera does not. Those empty slots
     belong on collections.html, which is the ledger and says "0
     frames" plainly; they do not belong in the nav or the burger,
     where every row wears a cover frame and an empty one would just
     be a blank tile. */
  var withFrames = TRIPS.filter(function (t) { return (t.photos || []).length; });
  var POSTS = window.POSTS || [];
  /* No post wears a portrait. There is one author, the journal's
     masthead already carries his face, and a column of the same
     36px photograph forty times over told the reader nothing it
     hadn't already said. What marks where a post starts is the
     dateline and the hairline above it — see THE JOURNAL in
     css/review.css. */
  var PINS = window.PINS || [];
  var GAMES = window.GAMES || [];
  var WRITING = window.WRITING || [];

  /* WHERE THIS PAGE IS. Empty for every page on the site, because they
     all live at the repo root and a relative href is what lets you open
     one off the disk. 404.html is the exception — GitHub Pages serves
     that one file at whatever path was missing, so a relative link
     written into it resolves against a directory that does not exist —
     and scripts/shell.js gives it <meta name="hl-base" content="/">.
     Every href THIS file writes has to go through it. */
  var BASE = (function () {
    var m = document.querySelector('meta[name="hl-base"]');
    return (m && m.getAttribute("content")) || "";
  })();
  function href(rel) { return esc(BASE + rel); }
  /* A collection's own page. Each one is a real file — <slug>.html,
     generated by scripts/shell.js — rather than gallery.html?trip=slug,
     so it can carry its own title and its own share card. */
  function tripHref(t) { return href(t.slug + ".html"); }

  /* A standalone blog post travels as a tiny synthetic trip so its
     tiles and the lightbox treat the frames like any other set. */
  var postTrips = {};
  function tripBySlug(slug) {
    if (postTrips[slug]) return postTrips[slug];
    return TRIPS.filter(function (t) { return t.slug === slug; })[0];
  }
  /* A post can carry its own frames — what came off the phone while
     it was happening — instead of pointing into the collection's
     edited set. They travel as a synthetic trip so the tiles and
     the lightbox treat them like any other set. */
  function beatSet(trip, b, key) {
    if (!b.photos || !b.photos.length) return { trip: trip, shots: b.shots || [] };
    var slug = "live-" + (trip.slug || "post") + "-" + key;
    var t = postTrips[slug] || (postTrips[slug] = {
      slug: slug, gallery: false, place: trip.place || "", nav: trip.nav || "", short: trip.short || "",
      when: trip.when || "", photos: b.photos
    });
    return { trip: t, shots: b.photos.map(function (_, i) { return i; }) };
  }
  /* A standalone journal entry belongs to no collection, so it gets a
     synthetic trip of its own — nowhere to click through to, but the
     lightbox can page its frames like any other set. */
  function postTrip(p, i) {
    var slug = "post-" + i;
    return postTrips[slug] || (postTrips[slug] = {
      slug: slug, gallery: false, place: "", short: "", nav: "",
      when: "", photos: p.photos || []
    });
  }
  function allPhotos() {
    var out = [];
    TRIPS.forEach(function (t) {
      (t.photos || []).forEach(function (p) { out.push({ trip: t, photo: p }); });
    });
    return out;
  }
  function cover(t) {
    var ps = t.photos || [];
    if (t.cover) {
      for (var i = 0; i < ps.length; i++) if (ps[i].src === t.cover) return ps[i];
      return { src: t.cover, alt: t.place };
    }
    return ps[0] || null;
  }
  /* What a collection is called, everywhere it's named: the full
     billing when it has one ("Tame Impala: Deadbeat Tour with
     Djo"), else the short name, else the title. */
  function xpName(t) {
    return t.nav || t.short || t.place || "";
  }
  /* A collection's face: its stated cover, else the first frame
     that isn't a clip, else a clip's poster if it has one. An
     collection whose only frame is a video and whose video has no
     poster has no face at all, and says so with an empty tile
     rather than a white square. */
  function thumbSrc(t) {
    if (t.cover) return t.cover;
    var ps = t.photos || [];
    for (var i = 0; i < ps.length; i++) if (!ps[i].video) return ps[i].src;
    for (var j = 0; j < ps.length; j++) if (ps[j].poster) return ps[j].poster;
    return "";
  }
  /* "August 5, 2026 @ Bridgestone Arena" — the same line in the
     nav menu and on the collections index; a count stands in when
     a collection never said where it was */
  /* A `when` of just a year means the posted date is a sort key
     holding the given order, not a day this happened on. Print the
     year it claims rather than the date it was filed under, or the
     page invents a Tuesday in November that nobody went anywhere on. */
  function xpStamp(t) {
    var yearOnly = /^\d{4}$/.test(String(t.when || "").trim());
    return (!yearOnly && longDate(t.posted)) || esc(t.when);
  }

  function xpByline(t) {
    var n = (t.photos || []).length;
    return xpStamp(t) +
      (t.loc ? " @ " + esc(t.loc) : " · " + n + (n === 1 ? " frame" : " frames"));
  }
  var LONG_MONTHS = ["January", "February", "March", "April", "May", "June",
                     "July", "August", "September", "October", "November", "December"];
  /* "August 5, 2026" from a posted date, for bylines */
  function longDate(s) {
    var m = String(s || "").match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return "";
    return LONG_MONTHS[Number(m[2]) - 1] + " " + Number(m[3]) + ", " + m[1];
  }
  /* "August 5" — the same date with the year taken off, for lists
     that already carry the year in a heading above the row. */
  function longMonthDay(s) {
    var m = String(s || "").match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return "";
    return LONG_MONTHS[Number(m[2]) - 1] + " " + Number(m[3]);
  }
  var SHORT_MONTHS = ["Jan", "Feb", "Mar", "Apr", "May", "Jun",
                      "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"];
  /* A JOURNAL DATE reads "Aug 11" — short enough to sit beside a place
     without competing with it, and still a date rather than a code.
     The year is dropped while it is still this year and only earns its
     space once it is telling you something: "Jun 20, 2024". Computed
     off the real clock, so a 2026 post starts showing its year on its
     own the moment 2027 arrives. */
  function postDate(s) {
    var m = String(s || "").match(/^(\d{4})-(\d{2})-(\d{2})/);
    if (!m) return "";
    var day = SHORT_MONTHS[Number(m[2]) - 1] + " " + Number(m[3]);
    return Number(m[1]) === new Date().getFullYear() ? day : day + ", " + m[1];
  }
  function clock(s) {
    var n = Math.round(s);
    return Math.floor(n / 60) + ":" + String(n % 60).padStart(2, "0");
  }
  /* On a wall a clip holds still under a play badge until you open
     it — a grid of moving frames fights the photographs beside it.
     (The journal used to run them muted and looping behind a speaker
     button; a post's clip now carries ordinary controls instead, so
     the autoplay watcher and the speaker went with the thread.) */
  function playSafely(v) {
    var p = v.play();
    /* a browser that refuses autoplay rejects rather than throwing */
    if (p && p.catch) p.catch(function () {});
  }
  /* `capped` asks for the caption as text under the frame rather than
     as a pill that only shows on hover. A collection's own wall takes
     it — the writing there is half the point of the page. The front
     wall doesn't: there the picture is the whole message. */
  function shotHtml(t, p, i, capped, lead) {
    var ratio = p.w && p.h ? ' style="aspect-ratio:' + Number(p.w) + "/" + Number(p.h) + '"' : "";
    /* Every frame is its own shape, on the wall and on a collection
       page alike, and `ratio` above is the whole mechanism: the box
       is the picture.

       Two earlier schemes are gone. `--fw` sized each frame by the
       square root of its aspect so an upright and a landscape covered
       equal area. `.shot--wide` / `.shot--tall` replaced it by sorting
       every frame into one of two boxes — 4:5 or 5:4 — with
       object-fit: cover trimming the difference; that bought an even
       grid at the price of 14.8% of the average photograph, and 21.3%
       of the worst. Nothing reads either now. See css/review.css,
       under the .stream-grid rules. */
    /* A clip's own surface opens the viewer; only the speaker
       button swallows the press. */
    if (p.video) {
      /* A clip on a wall holds a frame under a play badge — #t=0.1 is
         what paints that frame instead of a black box — and opens to
         play in the viewer. */
      var badge = '<span class="vid-badge" aria-hidden="true">' +
        '<svg viewBox="0 0 24 24"><path fill="currentColor" d="M9 6.5v11a1 1 0 0 0 1.5.87l9-5.5a1 1 0 0 0 0-1.74l-9-5.5A1 1 0 0 0 9 6.5Z"/></svg></span>';
      return '<figure class="shot shot--video">' +
        '<div class="vid">' +
          '<video src="' + esc(p.src) + '#t=0.1' +
          '" playsinline preload="metadata" muted' +
          (p.poster ? ' poster="' + esc(p.poster) + '"' : "") + ratio + "></video>" +
          badge +
          '<button class="vid-open" type="button" aria-label="View larger: ' +
            esc(p.alt || p.caption || t.place) + '" data-trip="' + esc(t.slug) + '" data-i="' + i + '"></button>' +
          (p.seconds ? '<span class="vid-dur">' + clock(p.seconds) + "</span>" : "") +
        "</div>" +
        (p.caption
          ? '<figcaption class="shot-cap">' + esc(p.caption) +
            '<span class="shot-credit">Cody Heart</span></figcaption>'
          : "") +
        "</figure>";
    }
    /* A frame with nothing written under it says nothing, rather than
       holding an empty line.

       There used to be a second caption treatment here: `.shot-pill`,
       a translucent lozenge laid over the bottom-left of the frame,
       shown on hover and used wherever `capped` was false — the front
       wall. It is gone. Hover is a desktop affordance, so it needed a
       `@media (hover: none)` companion to be reachable at all on a
       phone, and that rule pinned the lozenge PERMANENTLY OPEN on
       every frame: a wall of photographs each wearing a grey label it
       could not put down. The fix is not to hide it below some
       breakpoint — a caption you have to guess at is not a caption —
       it is that the wall doesn't want words on top of the pictures at
       any width. Captions still live in the data and still read out
       through the button's aria-label; they simply aren't painted over
       the frame. `capped` stays because the collection page's
       figcaption is a real, non-overlapping caption. */
    var cap = p.caption && capped
      ? '<figcaption class="shot-cap">' + esc(p.caption) + "</figcaption>" : "";
    return '<figure class="shot' + (lead ? " shot--lead" : "") + '">' +
      /* A button's children are presentational, so the <img alt> below
         never reaches a screen reader — the tile's name is this label
         and nothing else. Most frames carry no caption but every one
         carries a written alt, so the alt leads: otherwise a reader
         hears the trip name a dozen times in a row. */
      '<button class="shot-btn" type="button" data-trip="' + esc(t.slug) + '" data-i="' + i + '" aria-label="View larger: ' + esc(p.alt || p.caption || t.place) + '">' +
      /* the lead is the first thing on the page and above the fold on
         every screen — it is fetched outright rather than lazily, so
         the page doesn't open on an empty box */
      '<img src="' + esc(p.src) + '" alt="' + esc(p.alt || "") + '" ' +
      (lead ? 'loading="eager" fetchpriority="high"' : 'loading="lazy"') + ratio + ">" +
      "</button>" + cap + "</figure>";
  }

  /* Lightbox: one <dialog>, shared by any page that renders shots. It
     opens on a set rather than a single frame — whatever sat alongside
     the one you tapped — so you can keep going with an arrow, a key or
     a thumb. Entries carry their own trip, so the best-of wall can
     page straight across events. */
  var lb = { list: [], at: 0 };

  function pad2(n) { return (n < 10 ? "0" : "") + n; }

  /* The set loops. A click on the last frame comes round to the first
     rather than stopping dead, which is what the reference viewer
     does and what keeps the picture-as-next-button honest — there is
     no disabled state to see, so there must be no dead end to hit. */
  function lbStep(dlg, delta) {
    var n = lb.list.length;
    if (!n) return;
    lbShow(dlg, ((lb.at + delta) % n + n) % n);
  }

  function lbShow(dlg, k) {
    if (k < 0 || k >= lb.list.length) return;
    lb.at = k;
    lb.trip = lb.list[k].t;
    var p = lb.trip.photos[lb.list[k].i];
    if (!p) return;
    var img = dlg.querySelector("img");
    var vid = dlg.querySelector(".lb-video");
    /* a clip opens full screen and plays itself, like the stills do */
    if (p.video) {
      img.hidden = true;
      img.removeAttribute("src");
      if (vid) {
        vid.hidden = false;
        if (vid.getAttribute("src") !== p.src) vid.src = p.src;
        vid.muted = true;
        playSafely(vid);
      }
    } else {
      if (vid) { vid.pause(); vid.hidden = true; vid.removeAttribute("src"); }
      img.hidden = false;
      img.src = p.src;
    }
    img.alt = p.alt || "";
    /* Nothing is written under the picture. The viewer used to carry
       the frame's caption there, and before that the caption plus the
       collection and its date; the reference shows the photograph and
       the bar and nothing else, and that is the whole of it now. The
       words are not lost — they are on the wall's hover pill, in the
       alt text, and on the collection's own page. */
    var title = dlg.querySelector(".lb-title");
    if (title) title.textContent = xpName(lb.trip);
    var dl = dlg.querySelector(".lightbox-dl");
    if (dl) dl.href = p.src;
    var many = lb.list.length > 1;
    dlg.classList.toggle("has-set", many);
    var count = dlg.querySelector(".lb-count");
    if (count) count.textContent = many ? pad2(k + 1) + "/" + pad2(lb.list.length) : "";
  }

  function bindLightbox() {
    var dlg = document.getElementById("lightbox");
    if (!dlg || typeof dlg.showModal !== "function") return;

    /* the close, arrows and tally live here rather than in every
       page's markup */
    if (!dlg.querySelector(".lb-bar")) {
      var fig = dlg.querySelector("figure");
      if (fig && !fig.querySelector(".lb-video")) {
        fig.insertAdjacentHTML("afterbegin",
          '<video class="lb-video" playsinline loop controls hidden></video>');
      }
      /* One bar across the top: which collection this is and where you
         are in it on the left, what you can do with the frame on the
         right. The side arrows are gone — the picture is the next
         button — and so is the centred tally, which the count in the
         bar replaces. */
      dlg.insertAdjacentHTML("afterbegin",
        '<header class="lb-bar">' +
          '<span class="lb-bar__side">' +
            '<span class="lb-title"></span>' +
            '<span class="lb-count"></span>' +
          '</span>' +
          '<span class="lb-bar__side lb-bar__side--end">' +
            '<button class="lb-close" type="button" aria-label="Close image viewer">' +
              '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.75" ' +
              'stroke-linecap="round" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg>' +
            '</button>' +
          '</span>' +
        "</header>");
      /* the download had a fixed corner of its own; it belongs in the
         bar beside the close, so the pages' markup keeps the link and
         the viewer decides where it sits */
      var end = dlg.querySelector(".lb-bar__side--end");
      var dl = dlg.querySelector(".lightbox-dl");
      var dlWrap = dlg.querySelector(".lightbox-bar");
      if (dl && end) end.insertBefore(dl, end.firstChild);
      if (dlWrap) dlWrap.remove();
    }

    document.addEventListener("click", function (e) {
      var btn = e.target.closest(".shot-btn, .vid-open, .frame-btn");
      if (!btn) return;
      var trip = tripBySlug(btn.getAttribute("data-trip"));
      if (!trip) return;
      var here = Number(btn.getAttribute("data-i"));
      /* The set you page through is whatever the frame belongs to: a
         whole journal post or a whole note — passages and all, so a
         post's frames read as one roll even when its beats carried
         their own — else the grid the frame shares. */
      /* A page can name the set explicitly. The collection page needs
         it: its lead frame sits outside the grid, so without this the
         lead would open as a set of one and the wall as another.
         Checked FIRST and separately — `closest` with both in one
         selector would return the nearer `.stream-grid` and the
         wrapper would never win. */
      var box = btn.closest("[data-lbset]") || btn.closest(".post, .stream-grid");
      if (box) {
        lb.list = Array.prototype.map.call(box.querySelectorAll("[data-trip][data-i]"), function (b) {
          return { t: tripBySlug(b.getAttribute("data-trip")), i: Number(b.getAttribute("data-i")) };
        }).filter(function (en) { return en.t; });
      } else {
        lb.list = [{ t: trip, i: here }];
      }
      var start = -1;
      lb.list.some(function (en, k) {
        if (en.t === trip && en.i === here) { start = k; return true; }
        return false;
      });
      lbShow(dlg, start < 0 ? 0 : start);
      dlg.showModal();
    });

    dlg.addEventListener("click", function (e) {
      if (e.target.closest(".lightbox-dl")) return;
      if (e.target.closest(".lb-close")) { dlg.close(); return; }
      /* the bar is chrome, not a way out — a press that lands on the
         name or the count should do nothing at all */
      if (e.target.closest(".lb-bar")) return;
      /* a clip owns its surface: its own controls are sitting on it */
      if (e.target.closest(".lb-video")) return;
      /* THE PICTURE IS THE NEXT BUTTON. It reaches the edges of the
         mat, so anywhere on the white counts — but only when there is
         somewhere to go; a lone frame still closes on a press. */
      if (e.target.closest("img") && lb.list.length > 1) { lbStep(dlg, 1); return; }
      dlg.close();
    });
    dlg.addEventListener("close", function () {
      var v = dlg.querySelector(".lb-video");
      if (v) v.pause();
    });

    document.addEventListener("keydown", function (e) {
      if (!dlg.open) return;
      if (e.key === "ArrowRight") lbStep(dlg, 1);
      if (e.key === "ArrowLeft") lbStep(dlg, -1);
    });

    /* a thumb flick, the way you'd move through an album */
    var x0 = null;
    dlg.addEventListener("touchstart", function (e) {
      x0 = e.changedTouches[0].clientX;
    }, { passive: true });
    dlg.addEventListener("touchend", function (e) {
      if (x0 === null) return;
      var dx = e.changedTouches[0].clientX - x0;
      x0 = null;
      if (Math.abs(dx) < 45) return;
      e.stopPropagation();
      lbStep(dlg, dx < 0 ? 1 : -1);
    });
  }
  /* A strip of frames used to be a "reel": a track with hover arrows,
     a live counter under it, and a settle pass that measured whether
     it overflowed at all. Only the journal ever built one, and a post
     now carries a plain scroll-snapping strip whose overflow past the
     card edge is the whole affordance — so the arrows, the counter and
     the measuring went with the thread. What is left is the quiet
     sweep below: a frame whose file is missing takes its figure with
     it rather than showing a broken-image icon, and empties the strip
     or the block if it was the last one, so nothing is left holding a
     gap where a picture was. */
  function sweepBrokenFrames() {
    document.addEventListener("error", function (e) {
      var img = e.target;
      if (!img || img.tagName !== "IMG" || !img.classList ||
          !img.classList.contains("frame")) return;
      var fig = img.closest("figure");
      if (!fig) { img.remove(); return; }
      var box = fig.parentNode;
      fig.remove();
      while (box && box.classList && !box.children.length &&
             (box.classList.contains("strip") || box.classList.contains("media"))) {
        var up = box.parentNode;
        box.remove();
        box = up;
      }
    }, true);
  }

  bindLightbox();
  sweepBrokenFrames();



  /* ----------------------------------------------------------
     COLLECTION page — one trip.

     Which one comes from <meta name="hl-trip"> when the page is one of
     the generated per-collection pages (<slug>.html), and from ?trip=
     otherwise. The meta wins because it is the page's own identity,
     written into the file by scripts/shell.js alongside the title and
     the share card that describe the same collection; the query string
     is how gallery.html still works for links posted before those
     pages existed.
     ---------------------------------------------------------- */
  var galleryShots = document.getElementById("galleryShots");
  if (galleryShots && TRIPS.length) {
    var slug = "";
    var slugMeta = document.querySelector('meta[name="hl-trip"]');
    if (slugMeta) slug = slugMeta.getAttribute("content") || "";
    if (!slug) {
      try { slug = new URLSearchParams(location.search).get("trip") || ""; } catch (e) {}
    }
    var trip = TRIPS.filter(function (t) { return t.slug === slug; })[0] || TRIPS[0];

    document.title = xpName(trip) + " — Cody Heart Photography";
    var tEl = document.getElementById("galleryTitle");
    if (tEl) tEl.textContent = xpName(trip);
    /* the bar's scroll-title carries the collection's full billing */
    var navTitle = document.querySelector(".nav__scrolltitle");
    if (navTitle) navTitle.textContent = xpName(trip);
    var crumbEl = document.getElementById("crumbTrip");
    if (crumbEl) crumbEl.textContent = xpName(trip);
    /* NO PROSE ON AN EXPERIENCE PAGE. The line that used to sit under
       the title said why the day happened — "bought the tickets for
       Djo months ago" — which is the evening, not the room. The
       evening has a home and it is the journal; what belongs here is
       the pictures and the few facts that fix them in time.

       `[about]` still parses and trips still carry `note`, so nothing
       written has been thrown away. Nothing on this page reads it. */
    /* A collection has two halves, and they weigh the same. The
       FRAMES are the pictures, edited and chosen after the fact.
       The NOTES are what was written from inside it, and whatever
       came off the phone at the time. A new collection often starts
       as notes alone and grows its frames when there's time at a
       computer; either half on its own is still the record. */
    /* Every clip the collection holds shows in Video, whether or not
       a post also shows it — the post is the moment it went up, the
       section is where you go to watch. Stills don't double up: the
       wall takes the edited ones, the posts keep the rest. */
    /* AN EXPERIENCE PAGE IS THE PICTURES. It used to run a Notes
       section under the wall carrying what was written at the time,
       and the wall then had to EXCLUDE any frame a note had already
       shown so nothing appeared twice. With the notes gone the split
       goes with them: every still is on the wall. The writing still
       exists and still has a home — it is the journal. */
    var picks = [], clips = [];
    (trip.photos || []).forEach(function (p, i) {
      if (p.video) clips.push({ p: p, i: i });
      else picks.push({ p: p, i: i });
    });

    /* THE DETAILS OF THE SHOOT, on one line and in one voice: when,
       where, what on. They are all the same kind of fact and they
       belong together.

       This was briefly two lines — the date set large in mono directly
       under the title, the counts small and grey below the note — which
       put four different typographic treatments in four consecutive
       lines and read as though the date and the camera were unrelated
       to each other. They aren't. The date still leads the run, because
       it is the one that makes the page a record rather than an album,
       but it leads it at the same size as everything beside it.

       The counts came out after that. How many frames there are is
       something you can see by scrolling, and it described the page
       rather than the day — which is the opposite of what this line is
       for. The collections index still counts them, because there the
       count is how you tell the collections apart. */
    var whenEl = document.getElementById("galleryWhen");
    if (whenEl) {
      var facts = [xpStamp(trip)];
      if (trip.loc) facts.push(esc(trip.loc));
      /* No lens. A body dates a picture — "Sony RX100 VII" will read
         as a period detail soon enough, the same way the year does —
         but a lens designation dates nothing and runs to thirty-odd
         characters of product name, which unbalanced the plate and
         read as a spec sheet in either case. The camera stays because
         it is a fact about when; the glass was a fact about kit. */
      if (trip.camera) facts.push(esc(trip.camera));
      whenEl.innerHTML = facts.join(" · ");
    }

    /* THE LEAD, AND ITS PLATE. One frame runs large above the grid so
       the page has a way in, and the title and date sit directly under
       it, aligned to ITS edges rather than the page's.

       That pairing is the whole fix. The lead is centred and capped —
       it keeps its own proportions, so its width is whatever its shape
       makes it, and it cannot line up with a grid that runs gutter to
       gutter. Left on its own it read as floating. Given the plate to
       stand on, the two become one object: a print with its label. The
       grid keeps the page's left edge; the lead keeps its own.

       Which frame is not a new decision: the first flagged `best` in
       trip.txt, the edit already made at posting time. It is pulled
       OUT of the grid so it doesn't appear twice, and the lightbox
       set is rooted on the [data-lbset] wrapper that holds both, so
       paging still runs lead-then-wall in one sequence. */
    var leadEl = document.getElementById("galleryLead");
    var leadSec = document.getElementById("leadSec");
    if (leadEl) {
      if (picks.length) {
        var leadIdx = 0;
        picks.some(function (en, k) {
          if (en.p.best) { leadIdx = k; return true; }
          return false;
        });
        var leadEntry = picks.splice(leadIdx, 1)[0];
        leadEl.innerHTML = shotHtml(trip, leadEntry.p, leadEntry.i, false, true);
      } else {
        /* Most collections are logged long before their photographs
           exist. Such a page holds the same shape open rather than
           collapsing to a title on white — a blank standing where the
           lead will go, so the plate has something to sit on and every
           collection page reads the same whether or not it has been
           edited yet. Flat and inert: nothing is loading here and
           nothing is about to, so it must not shimmer like it is. */
        leadEl.innerHTML = '<span class="xp-blank xp-blank--lead" aria-hidden="true"></span>';
      }
      /* one title on the page, moved under the frame it belongs to */
      var plate = document.getElementById("leadPlate");
      var head = document.querySelector(".xp-head");
      if (plate && head) plate.appendChild(head);
      leadSec.hidden = false;
    }

    var framesSec = document.getElementById("framesSec");
    if (picks.length) {
      /* captions read as text here, not as a pill on hover */
      galleryShots.innerHTML = picks.map(function (en) {
        /* images, not images-and-writing: the caption stays on the
           hover pill and in the lightbox, same as the front wall */
        return shotHtml(trip, en.p, en.i, false);
      }).join("");
      if (framesSec) framesSec.hidden = false;
    } else if (!clips.length) {
      /* the wall held open the same way, in the two shapes it uses */
      var slots = "";
      for (var b = 0; b < 10; b++) {
        slots += '<span class="shot xp-blank ' +
          (b % 3 === 1 ? "xp-blank--wide" : "xp-blank--tall") + '" aria-hidden="true"></span>';
      }
      galleryShots.innerHTML = slots;
      if (framesSec) framesSec.hidden = false;
    }

    /* The clips stand apart from the stills — they play themselves,
       and a wall of moving frames would fight the photographs. */
    var vidEl = document.getElementById("galleryClips");
    var vidSec = document.getElementById("clipsSec");
    if (vidEl && clips.length) {
      vidEl.innerHTML = clips.map(function (en) {
        return shotHtml(trip, en.p, en.i);
      }).join("");
      if (vidSec) vidSec.hidden = false;
    }

    /* `emptyEl` was READ HERE WITHOUT EVER BEING DECLARED. Reading an
       undeclared name is a ReferenceError, so this line threw on every
       single collection page and took the rest of the module with it —
       which is why the Collections dropdown and the mobile menu's list
       of collections, both built further down, were empty on every one
       of them. Declare it. */
    var emptyEl = document.getElementById("galleryEmpty");
    if (emptyEl && !picks.length && !clips.length) emptyEl.hidden = false;
  }

  /* ----------------------------------------------------------
     THE WALL — the front door shows only the keepers: every
     frame flagged `best: true`, one unbroken wall, newest trip
     first. The full sets live on the event pages, indexed just
     below the wall.
     ---------------------------------------------------------- */
  function bestPhotos() {
    var out = [];
    TRIPS.forEach(function (t) {
      (t.photos || []).forEach(function (p, i) {
        if (p.best) out.push({ t: t, p: p, i: i });
      });
    });
    return out;
  }
  var bestWall = document.getElementById("bestWall");
  if (bestWall && TRIPS.length) {
    var picks = bestPhotos();
    bestWall.innerHTML = '<div class="stream-grid">' +
      picks.map(function (en) { return shotHtml(en.t, en.p, en.i); }).join("") + "</div>";
    var statsText = picks.length + " keepers · " + TRIPS.length + " collections · newest first";
    Array.prototype.forEach.call(document.querySelectorAll(".photo-stats"), function (el) {
      el.textContent = statsText;
    });
  }
  /* ----------------------------------------------------------
     THE EXPERIENCES INDEX — every one on its own page, in the
     log's register: a face, its name, when and where, and the
     count of frames holding the right edge. Grouped by year.
     ---------------------------------------------------------- */
  var xpList = document.getElementById("experienceList");
  if (xpList && TRIPS.length) {
    /* THE LEDGER. Not a grid of tiles — that is the front wall's job,
       and doing it twice would make this page a second homepage. This
       is a dated list: the year carries the structure, each collection
       is one ruled row, and one frame rides along as evidence.

       Every row wears the same plate as the collection page it opens:
       the name in Cheltenham over a line of facts in the nav's sans.
       Same two faces, same order, so the index and the page read as
       one thing rather than two designs.

       Rows with nothing shot yet keep a blank in the frame slot for
       the same reason the pages do — flat and inert, because nothing
       is loading and nothing is about to. */
    /* YEAR SECTIONS, newest year first. Each year is a
       <section class="xp-era"> with the year as an h2 above its rows.

       These came out once, on the argument that headings only read as
       structure when the years are full and this list would leave a
       year standing over a single row. That is still true of 2023 and
       2019 — one collection each — but Cody asked for the years back
       on 2026-08-13, and the spine is worth the thin sections: the
       whole argument of the site is that a picture is how a place was
       on a day, so when should be the thing you scroll past. If the
       sparse years start to grate, collapse the tail into one section
       rather than dropping the headings again.

       Ordering is EXPLICIT here, newest to oldest, rather than trusting
       the order js/photos.js happens to be written in — that file is
       regenerated by the poster and its order is not a contract. */
    /* THE FEATURED COLLECTION. One trip carries `featured: true` in
       js/photos.js. It used to sort to the top of the whole list; with
       the years back it leads ITS OWN YEAR instead, because a 2026 row
       hoisted above the 2026 heading would just look like a bug. It is
       still an ordinary row — same size, same treatment — it just goes
       first among its neighbours. `featured` is editorial, like `best`;
       scripts/post.js prints it back out so a re-post cannot drop it,
       and nothing breaks if no trip carries it. */
    function tripYear(t) {
      var m = String(t.posted || "").match(/^(\d{4})/) ||
              String(t.when || "").match(/(\d{4})/);
      return m ? Number(m[1]) : 0;
    }
    /* Sortable to the day. A collection that only ever claimed a year
       sorts to the end of that year rather than the start of it, so a
       dated row never falls below an undated one from the same year. */
    function tripKey(t) {
      var m = String(t.posted || "").match(/^\d{4}-\d{2}-\d{2}/);
      return m ? m[0] : tripYear(t) + "-00-00";
    }

    function rowFacts(t, stills) {
      var yearOnly = /^\d{4}$/.test(String(t.when || "").trim());
      /* The year is in the heading directly above, so the row does not
         say it twice: a full date drops to month and day, and a
         collection that only ever claimed a year says nothing about
         when at all. (While the headings were gone this row carried the
         whole date, because otherwise nothing on the page did.) */
      var day = yearOnly ? "" : longMonthDay(t.posted);
      var n = stills.length, nclips = (t.photos || []).length - n, f = [];
      if (day) f.push(day);
      if (t.loc) f.push(esc(t.loc));
      if (n) f.push(n + (n === 1 ? " frame" : " frames"));
      else if (nclips) f.push(nclips + (nclips === 1 ? " clip" : " clips"));
      else f.push("no frames yet");
      return f;
    }

    var xhtml = "";
    /* A copy — TRIPS is shared with the front wall and the nav menu,
       and sorting it in place would reorder those too. */
    var ordered = TRIPS.slice().sort(function (a, b) {
      var ya = tripYear(a), yb = tripYear(b);
      /* newest year first; anything we can't date at all falls to the
         bottom, since tripYear gives it 0 */
      if (ya !== yb) return yb - ya;
      var fa = a.featured ? 1 : 0, fb = b.featured ? 1 : 0;
      if (fa !== fb) return fb - fa;
      var ka = tripKey(a), kb = tripKey(b);
      return ka < kb ? 1 : ka > kb ? -1 : 0;
    });

    var era = null;
    ordered.forEach(function (t) {
      var year = tripYear(t);
      if (year !== era) {
        if (era !== null) xhtml += "</section>";
        xhtml += '<section class="xp-era">' +
          '<h2 class="xp-era__year">' + (year || "Undated") + "</h2>";
        era = year;
      }
      var stills = (t.photos || []).filter(function (p) { return !p.video; });
      /* the frame it leads with is the frame its own page leads with */
      var lead = stills.filter(function (p) { return p.best; })[0] || stills[0];

      /* The row carries the whole date now. It used to drop the year
         and, for a collection that only ever claimed one, say nothing
         at all — both because the year sat in a heading directly above
         it. With the headings gone that leaves rows reading "Bridgestone
         Arena · 24 frames" with no date anywhere, so the year comes
         back: the full date when there is one, the bare year when the
         collection only ever claimed a year. */
      var facts = rowFacts(t, stills);

      /* THE PHOTOGRAPHS CARRY THE ROW. Text is a narrow column on the
         left; the frames take everything else. One thumbnail beside a
         name made this an index with a picture stuck to it — the point
         of the page is the work, so the work gets the measure.

         Ten are laid out and the run simply clips at the edge of the
         measure, so it fills the width on any screen rather than
         running out on a wide one. Each takes one of the wall's own two
         boxes so the index speaks the same language: wider than tall
         gets the 5:4, the rest the 4:5. Height is fixed and width
         follows the shape, so a mixed run still lines up top and
         bottom.

         A collection with nothing shot yet holds ten slots open in
         the same rhythm. Flat and inert — nothing is loading — but the
         row keeps its shape, so the page reads the same whether the
         pictures have been edited yet or not.

         The run OPENS on `lead` — the same frame the collection's own
         page leads with — and the rest follow in their posted order.
         This used to be computed and then thrown away: the row just
         sliced the first ten, so a collection whose chosen frame sat
         further down led the index with whatever happened to be first,
         usually a journal beat rather than the edit. Rows whose lead is
         already the first still are unaffected. */
      var shots = (lead ? [lead].concat(stills.filter(function (p) { return p !== lead; }))
                        : stills).slice(0, 10);
      var frames = "";
      if (shots.length) {
        frames = shots.map(function (sp) {
          var wide = sp.w && sp.h && Number(sp.w) > Number(sp.h);
          return '<span class="xp-row__frame' + (wide ? " xp-row__frame--wide" : "") + '">' +
            '<img src="' + esc(sp.src) + '" alt="" loading="lazy" decoding="async"></span>';
        }).join("");
      } else {
        for (var q = 0; q < 10; q++) {
          frames += '<span class="xp-row__frame' + (q % 3 === 1 ? " xp-row__frame--wide" : "") +
            '"><span class="xp-blank" aria-hidden="true"></span></span>';
        }
      }

      xhtml += '<a class="xp-row" href="' + tripHref(t) + '">' +
        '<span class="xp-row__text">' +
          '<span class="xp-row__name">' + esc(xpName(t)) + "</span>" +
          '<span class="xp-row__meta">' + facts.join(" · ") + "</span>" +
        "</span>" +
        '<span class="xp-row__frames">' + frames + "</span>" +
        "</a>";
    });
    if (era !== null) xhtml += "</section>";
    xpList.innerHTML = xhtml;

    var xpStats = document.getElementById("experienceStats");
    if (xpStats) {
      xpStats.textContent = TRIPS.length + " collections · " +
        allPhotos().length + " frames · newest first";
    }
  }

  /* The collections on the front page: one ruled row each into
     its own page, where any frame goes. (Data still says TRIPS.) */

  /* ==========================================================
     WHAT A FRAME DOES WHERE THE WRITING IS THE POINT.

     Two places on this site put photographs under prose: a post
     in the journal and a note on a collection's page. They are
     deliberately different objects — a post is one of forty and
     has to say which outing it came from; a note sits on a page
     whose masthead already said all that — but a photograph must
     not behave differently in the two of them. So the media
     rules live here, once, and both call them.
     ========================================================== */

  /* ---------- what a piece of media IS ----------
     One field decides it. `youtube` wins; otherwise the extension
     does the work, so a .gif needs no new field at all — it rides the
     image path and animates on its own. */
  function kindOf(m) {
    if (!m) return "photo";
    if (m.youtube) return "youtube";
    if (m.video === true || /\.(mp4|mov|m4v|webm)$/i.test(m.src || "")) return "video";
    if (/\.gif$/i.test(m.src || "")) return "gif";
    return "photo";
  }
  /* the id out of whatever was pasted — a watch URL, a youtu.be
     short link, an embed, a short, or the bare id itself */
  function tubeId(v) {
    var s = String(v || "");
    var m = s.match(/(?:v=|youtu\.be\/|embed\/|shorts\/)([\w-]{6,})/);
    return m ? m[1] : s;
  }
  function mediaEl(t, p, i, single) {
    var k = kindOf(p);
    var box = (p.w && p.h)
      ? ' width="' + Number(p.w) + '" height="' + Number(p.h) + '"' : "";
    /* An iframe, not a script — nothing is fetched from a CDN at parse
       time, and nocookie keeps it from setting one before a click. */
    if (k === "youtube") {
      return '<div class="tube"><iframe src="https://www.youtube-nocookie.com/embed/' +
        esc(tubeId(p.youtube)) + '" title="' + esc(p.alt || p.caption || "YouTube video") +
        '" loading="lazy" allow="accelerometer; clipboard-write; encrypted-media; picture-in-picture"' +
        " allowfullscreen></iframe></div>";
    }
    /* A clip of his own: controls, not autoplay, because a written
       video is watched on purpose rather than glanced at on the way
       past. It plays where it sits and never opens the viewer. */
    if (k === "video") {
      return '<video class="frame" data-kind="video" src="' + esc(p.src) + '"' + box +
        ' controls playsinline preload="metadata"' +
        (p.poster ? ' poster="' + esc(p.poster) + '"' : "") + "></video>";
    }
    /* A still or a GIF opens the viewer. The button is capped to the
       picture's own width when the shape is known: a `max-height`
       never reaches intrinsic sizing, so without this the click target
       and the focus ring of an upright frame would run the whole
       measure beside it. */
    var fit = single && p.w && p.h
      ? ' style="max-width:min(100%,calc(var(--frame-cap) * ' +
        (Math.round((Number(p.w) / Number(p.h)) * 1e4) / 1e4) + '))"'
      : "";
    return '<button class="frame-btn" type="button" data-trip="' + esc(t.slug) +
      '" data-i="' + i + '" aria-label="View larger: ' +
      esc(p.alt || p.caption || xpName(t) || "frame") + '"' + fit + ">" +
      '<img class="frame" data-kind="' + k + '" src="' + esc(p.src) + '" alt="' +
      esc(p.alt || "") + '"' + box + ' loading="lazy" decoding="async"></button>';
  }
  /* `caps` asks for the written caption under the frame. Only a written
     caption ever shows; `alt` stays where it belongs — it describes the
     picture for someone who cannot see it, and printing it underneath
     says the same thing twice.

     A JOURNAL POST passes false. The post's own words are right above
     the picture, so a caption under it is a second, quieter voice
     saying something about the same frame — and on a strip of four it
     was four of them. An EXPERIENCE PAGE passes true: there the writing
     beside each frame is half the reason the page exists. */
  function figureFor(t, p, i, single, caps) {
    return "<figure" + (single ? ' class="one"' : "") + ">" +
      mediaEl(t, p, i, single) +
      (caps && p.caption ? "<figcaption>" + esc(p.caption) + "</figcaption>" : "") +
      "</figure>";
  }
  /* ONE item sits in the column, capped by height so a portrait can't
     own the screen. TWO OR MORE become a strip that runs past the
     right edge and scroll-snaps. That overflow is the point: it says
     "there's more here" without a count badge, and it is the one place
     the column is allowed to break. */
  function mediaHtml(t, shots, caps) {
    if (!shots || !shots.length) return "";
    if (shots.length === 1) {
      var only = t.photos[shots[0]];
      return only ? '<div class="media">' + figureFor(t, only, shots[0], true, caps) + "</div>" : "";
    }
    var out = shots.map(function (i) {
      var p = t.photos[i];
      return p ? figureFor(t, p, i, false, caps) : "";
    }).join("");
    return out ? '<div class="media"><div class="strip">' + out + "</div></div>" : "";
  }


  /* ----------------------------------------------------------
     THE JOURNAL — one post per outing, newest first.

     WHAT THIS REPLACED. The journal used to be a THREAD: every
     beat of every collection was its own row, hairlined off from
     the one above, and a run of rows from one collection was
     drawn as a chain hanging off a connector rail. Three notes
     written across one afternoon in San Diego came out as three
     orphans, each re-introducing the same collection, the same
     venue and the same date to the reader who had just read it.

     An outing is one thing, so it is now one POST. Its beats are
     the PASSAGES inside it — words, then whatever was shot while
     those words were being written, then the next paragraph. A
     standalone entry is a post of its own. The chain, the rail,
     the per-row header line and the whole thread container went
     with them.

     THE HEADER IS THE DATE. No titles: `b.head` and `p.head`
     still live in the data and nothing renders them, because a
     headline over two sentences is a title on a note to yourself.
     The date carries the post and the place follows it in the
     quiet weight, which is what a blog has always done.
     ---------------------------------------------------------- */

  /* post-2026-08-09-deadbeat-tour — stable as long as the day and the
     slug are, which is what a permalink has to be */
  function anchorFor(e) {
    return "post-" + (String(e.date || "").slice(0, 10) || "x") +
      (e.slug ? "-" + e.slug : "") + (e.n ? "-" + e.n : "");
  }
  function monthOf(d) { return String(d || "").slice(0, 7); }
  function monthLabel(k) {
    var m = String(k).match(/^(\d{4})-(\d{2})$/);
    return m ? LONG_MONTHS[Number(m[2]) - 1] : String(k);
  }

  /* ONE NOTE, ONE POST. Every beat stands on its own — three notes
     written across a day at the zoo are three posts, not one post with
     three parts. Posting more than once a day is the point; they queue
     up in the column the way anything else does, newest first, each
     with its own date and its own permalink.

     (This has been both ways. Grouping an outing into a single post
     with its passages strung on a rail was tried and rejected: the
     relationship it drew was real but it made a day feel like one
     obligation rather than several cheap ones, which is the opposite
     of the point.) */
  function journalPosts() {
    var out = [];
    TRIPS.forEach(function (t) {
      var beats = (t.beats || []).slice();
      if (!beats.length) return;
      /* Beats read in the order they were written; when every one of
         them carries a time, that order is the clock's. */
      if (beats.every(function (b) { return !!b.time; })) {
        beats.sort(function (a, b) { return a.time < b.time ? -1 : a.time > b.time ? 1 : 0; });
      }
      beats.forEach(function (b, i) {
        var set = beatSet(t, b, i);
        out.push({
          date: b.time || t.posted || "",
          title: b.title || "",
          where: t.loc || "",
          slug: t.slug,
          /* several notes can share a day AND an outing, so the anchor
             takes the beat's index too or the permalinks collide */
          n: i,
          passages: [{ say: b.say || "", trip: set.trip, shots: set.shots }]
        });
      });
    });
    POSTS.forEach(function (p, i) {
      var t = postTrip(p, i);
      out.push({
        date: p.time || "", title: p.title || "", where: p.at || "", slug: "", n: 0,
        passages: [{
          say: p.say || "", trip: t,
          shots: (p.photos || []).map(function (_, k) { return k; })
        }]
      });
    });
    /* AT LEAST ONE OF. A post is valid with frames, or with words, or
       both — it is never required to have both. What it may not be is
       neither: an outing that was logged and then never written from
       and never shot is a collection, not a post, and it belongs on
       the index rather than as an empty card here. */
    out = out.filter(function (e) {
      return e.passages.some(function (p) { return p.say || p.shots.length; });
    });
    out.sort(function (a, b) { return a.date < b.date ? 1 : a.date > b.date ? -1 : 0; });
    return out;
  }

  /* EVERY POST CARRIES ITS OWN DATELINE. A previous pass suppressed it
     on a same-day run so the date wasn't repeated — but that made the
     first post of a day look structurally different from the two under
     it, and the ones without a header read as loose text with nothing
     holding them. Uniformity is worth more than avoiding a repeat, and
     at kicker size a repeat costs almost nothing. */
  function postHtml(e) {
    var id = anchorFor(e);
    /* THE TITLE IS WHATEVER THE POST IS ABOUT. Usually that is where you
       were — and where you were comes free, so most posts get a title
       without typing one — but it is not a location field. A post about
       the pizza is titled "The pizza"; a post about a clip somebody
       else made is titled with whatever you have to say about it.

         title:  what you wrote, if you wrote one     ← wins
         at:     a standalone post's own line
         loc:    the venue of the collection it belongs to
         date:   nothing else to say, so the date leads

       Falling back this way means old entries keep the venue they had
       and new ones can say anything, with no field to fill in unless
       you want to. */
    var place = e.title || e.where || "";
    var head = '<a class="post__head" id="' + esc(id) + '" href="#' + esc(id) + '">' +
      (place
        ? '<span class="post__title">' + esc(place) + "</span>" +
          '<span class="post__date">' + esc(postDate(e.date)) + "</span>"
        : '<span class="post__title">' + esc(postDate(e.date)) + "</span>") +
      "</a>";
    /* a passage with neither words nor frames is nothing — not an empty
       box, and not a gap where a paragraph would have been */
    var live = e.passages.filter(function (p) { return p.say || p.shots.length; });
    /* THE CARD holds all of it — the dateline, the words, and the
       frames. The photographs were briefly set outside it on the page,
       tied to the post by proximity alone; inside is what makes a post
       one object you can see the edges of. */
    var words = live.map(function (p) {
      return p.say ? '<p class="post__say">' + esc(p.say) + "</p>" : "";
    }).join("");
    var frames = live.map(function (p) {
      return mediaHtml(p.trip, p.shots, false);
    }).join("");
    /* a card with frames takes the full column: a strip has to have a
       width to overflow, and a picture shouldn't be sized by how long
       the sentence above it happened to be */
    var body = '<div class="bubble' + (frames ? " bubble--media" : "") + '">' +
      head + words + frames + "</div>";
    /* No tail. A post used to end with a row pointing at the collection
       it came from — cover thumb, label, name, chevron. It was the
       heaviest thing in the post and it repeated on every one of them,
       so a page of short entries read as a list of adverts for pages
       elsewhere. The nav's Collections menu already goes there, and the
       post itself is the point. */
    return '<article class="post">' + body + "</article>";
  }

  /* ---------- THE ARCHIVE ----------
     A month index in the right-hand margin, grouped by year. The
     house rule on this site is that filters belong inside the list
     they filter rather than in a control beside it — see HANDOFF.md.
     The journal is the one deliberate exception, asked for by name:
     it is the shape every blog has, the record runs back to 2019,
     and there is no way to put "September 2021" inside a stream that
     lazily renders the last eight posts. It is a card of the same
     material as the posts, so it reads as the second column of one
     object rather than as chrome floating in the margin. Do not copy
     this pattern anywhere else on the site. */
  function monthIndex(entries) {
    var order = [], seen = {};
    /* entries arrive newest first, so the months do too */
    entries.forEach(function (e) {
      var k = monthOf(e.date);
      if (!k) return;
      if (!seen[k]) { seen[k] = { key: k, n: 0 }; order.push(seen[k]); }
      seen[k].n++;
    });
    var years = [], byYear = {}, keys = [];
    order.forEach(function (m) {
      var y = m.key.slice(0, 4);
      if (!byYear[y]) { byYear[y] = { year: y, months: [] }; years.push(byYear[y]); }
      byYear[y].months.push(m);
      keys.push(m.key);
    });
    return { years: years, keys: keys };
  }
  function archiveHtml(years, total) {
    var row = function (key, name, n) {
      return '<button class="archive__row" type="button" data-month="' + esc(key) + '">' +
        '<span class="archive__name">' + esc(name) + "</span>" +
        '<span class="archive__n">' + n + "</span></button>";
    };
    var out = '<div class="archive__in">' +
      '<p class="archive__label">Archive</p>' +
      row("all", "All posts", total);
    years.forEach(function (g) {
      out += '<div class="archive__year"><span class="archive__y">' + esc(g.year) + "</span>";
      g.months.forEach(function (m) { out += row(m.key, monthLabel(m.key), m.n); });
      out += "</div>";
    });
    return out + "</div>";
  }

  var feedList = document.getElementById("feedList");
  if (feedList && (TRIPS.length || POSTS.length)) {
    var entries = journalPosts();
    var index = monthIndex(entries);
    /* THE MONTH FILTER IS OFF. Its markup was pulled from feed.html, so
       everything below that touches `#feedArchive` no-ops on its own —
       the machinery is left intact for when it comes back. The one
       thing that would NOT no-op is the `?month=` deep link: it would
       still filter the journal with no visible control to undo it, so
       it is only honoured while the archive is actually on the page. */
    var month = "all";
    if (document.getElementById("feedArchive")) {
      try {
        var asked = new URLSearchParams(location.search).get("month") || "";
        if (asked && index.keys.indexOf(asked) >= 0) month = asked;
      } catch (e) {}
    }

    var view = entries, vAt = 0;
    var sentinel = document.createElement("div");
    sentinel.className = "feed-sentinel";
    /* Batches keep a journal years deep light: eight posts at a time,
       more as the bottom nears. The unit is a whole post, so the fold
       can never land inside one. The while-loop matters — after a
       batch the sentinel can still be in view, and the observer alone
       won't re-fire for it. */
    var BATCH = 8;
    var fill = function () {
      var guard = 0;
      while (vAt < view.length && guard++ < 40 &&
             sentinel.getBoundingClientRect().top < window.innerHeight + 1200) {
        var out = "", n = 0;
        while (vAt < view.length && n < BATCH) { out += postHtml(view[vAt]); vAt++; n++; }
        sentinel.insertAdjacentHTML("beforebegin", out);
      }
      if (vAt >= view.length && watcher) watcher.disconnect();
    };
    var watcher = window.IntersectionObserver
      ? new IntersectionObserver(function (ens) {
          ens.forEach(function (en) { if (en.isIntersecting) fill(); });
        }, { rootMargin: "1200px 0px" })
      : null;

    var frameCount = function (list) {
      var n = 0;
      list.forEach(function (e) {
        e.passages.forEach(function (p) { n += p.shots.length; });
      });
      return n;
    };
    var show = function (key) {
      month = key;
      view = key === "all" ? entries
        : entries.filter(function (e) { return monthOf(e.date) === key; });
      vAt = 0;
      if (watcher) watcher.disconnect();
      feedList.innerHTML = "";
      feedList.appendChild(sentinel);
      if (!view.length) {
        sentinel.insertAdjacentHTML("beforebegin",
          '<p class="noscript-note">Nothing posted ' +
          (key === "all" ? "yet." : "that month.") + "</p>");
      } else if (!watcher) {
        /* no IntersectionObserver: render the lot at once rather than
           leaving the page holding a sentinel and nothing else */
        sentinel.insertAdjacentHTML("beforebegin",
          view.map(postHtml).join(""));
        vAt = view.length;
      } else {
        fill();
        if (vAt < view.length) watcher.observe(sentinel);
      }

      var stat = document.getElementById("feedStat");
      if (stat) {
        var f = frameCount(view);
        stat.textContent = view.length + (view.length === 1 ? " post" : " posts") +
          (f ? " · " + f + (f === 1 ? " frame" : " frames") : "") + " · " +
          (key === "all" ? "newest first" : monthLabel(key) + " " + key.slice(0, 4));
      }
      var rail = document.getElementById("feedArchive");
      if (rail) {
        Array.prototype.forEach.call(rail.querySelectorAll("[data-month]"), function (b) {
          var on = b.getAttribute("data-month") === key;
          b.classList.toggle("is-active", on);
          if (on) b.setAttribute("aria-current", "true");
          else b.removeAttribute("aria-current");
        });
      }
      /* the month is a place you can send someone, so it lives in the
         URL — replaced rather than pushed, because the back button
         belongs to the pages you came from, not to a filter */
      try {
        var u = new URL(location.href);
        if (key === "all") u.searchParams.delete("month");
        else u.searchParams.set("month", key);
        history.replaceState(null, "", u.pathname + u.search + u.hash);
      } catch (e) {}
    };

    /* The posts render first and on their own. Nothing below can stop
       them: if the archive never builds, the journal is still a
       journal. */
    show(month);

    var rail = document.getElementById("feedArchive");
    if (rail && entries.length) {
      rail.innerHTML = archiveHtml(index.years, entries.length);
      rail.hidden = false;
      rail.addEventListener("click", function (e) {
        var b = e.target.closest("[data-month]");
        if (b) show(b.getAttribute("data-month"));
      });
      /* mark whatever the URL asked for, now that the rows exist */
      Array.prototype.forEach.call(rail.querySelectorAll("[data-month]"), function (b) {
        var on = b.getAttribute("data-month") === month;
        b.classList.toggle("is-active", on);
        if (on) b.setAttribute("aria-current", "true");
      });
    }
  }


  /* ----------------------------------------------------------
     THE LEDGER — two pillars and the quiet rows. Photos is the
     front door; the events live as chips on the wall, not here.
     ---------------------------------------------------------- */
  var menuTrips = document.getElementById("menuTrips");
  if (menuTrips && TRIPS.length) {
    /* The way through to the full ledger wears a card like every other
       row — the same rounded square as the cover frames, so it reads as
       one of the options rather than a footnote underneath them. The
       count comes from the data, so it stays true as collections land. */
    var oldest = (TRIPS[TRIPS.length - 1] || {}).posted || "";
    var allDesc = TRIPS.length + (oldest ? ", back to " + oldest.slice(0, 4) : "");
    var allCard =
      '<div class="menu-item__tile menu-item__tile--all">' +
        '<svg class="icon-duo" viewBox="0 0 24 24" fill="none" aria-hidden="true">' +
          '<rect class="duo-a" x="3" y="3" width="8.4" height="8.4" rx="2.4"/>' +
          '<rect class="duo-b" x="12.6" y="3" width="8.4" height="8.4" rx="2.4"/>' +
          '<rect class="duo-b" x="3" y="12.6" width="8.4" height="8.4" rx="2.4"/>' +
          '<rect class="duo-a" x="12.6" y="12.6" width="8.4" height="8.4" rx="2.4"/>' +
        "</svg></div>" +
      '<div><span class="menu-item__title">See all collections</span>' +
      '<span class="menu-item__desc">' + esc(allDesc) + "</span></div>";

    /* The burger says what the desktop menu says, shorter: the four
       newest wearing their cover frame, then the way to the rest.
       Both are built from the same data, so posting updates both.
       Four, not the dropdown's six, because the sheet has a fold and
       the dropdown does not — at six this list ran 380px and pushed
       Elsewhere off the bottom of every phone. */
    if (menuTrips) {
      menuTrips.innerHTML =
        withFrames.slice(0, 4).map(function (t) {
          var src = thumbSrc(t);
          return '<a class="mobile-menu__item" href="' + tripHref(t) + '">' +
            '<div class="menu-item__tile menu-item__tile--photo' +
            (src ? "" : " menu-item__tile--empty") + '">' +
            (src ? '<img src="' + esc(src) + '" alt="" loading="lazy">' : "") +
            "</div><div>" +
            '<span class="menu-item__title">' + esc(xpName(t)) + "</span>" +
            '<span class="menu-item__desc">' + xpByline(t) + "</span></div></a>";
        }).join("") +
        '<a class="mobile-menu__item mobile-menu__all" href="' + href("collections.html") + '">' +
          allCard + "</a>";
    }
    /* The Trips dropdown in the top nav */
    var navTrips = document.getElementById("navTrips");
    if (navTrips) {
      /* the six newest, each wearing its cover frame; the rest live
         behind "See all collections" */
      navTrips.innerHTML =
        withFrames.slice(0, 6).map(function (t) {
          var src = thumbSrc(t);
          var byline = xpByline(t);
          return '<a class="menu-item" role="menuitem" href="' + tripHref(t) + '">' +
            '<div class="menu-item__tile menu-item__tile--photo' +
            (src ? "" : " menu-item__tile--empty") + '">' +
            (src ? '<img src="' + esc(src) + '" alt="" loading="lazy">' : "") +
            "</div><div>" +
            '<span class="menu-item__title">' + esc(xpName(t)) + "</span>" +
            '<span class="menu-item__desc">' + byline + "</span></div></a>";
        }).join("") +
        '<a class="menu-item menu-item--all" role="menuitem" href="' + href("collections.html") + '">' +
          allCard + "</a>";
    }
  }

  /* ----------------------------------------------------------
     PINS page
     ---------------------------------------------------------- */
  var pinList = document.getElementById("pinList");
  if (pinList && PINS.length) {
    pinList.innerHTML = PINS.map(function (p) {
      return '<li class="pin">' +
        '<a class="pin-title" href="' + esc(p.url) + '" target="_blank" rel="noopener">' +
          esc(p.title) + ' <span class="arrow" aria-hidden="true">↗</span></a>' +
        '<span class="pin-meta">' + esc(p.source) + (p.year ? " · " + esc(p.year) : "") + "</span>" +
        (p.note ? '<p class="pin-note">' + esc(p.note) + "</p>" : "") +
        "</li>";
    }).join("");
    var pc = document.getElementById("pinCount");
    if (pc) pc.textContent = PINS.length + " pins · in the order they were saved";
  }

  /* ----------------------------------------------------------
     GAMES page
     ---------------------------------------------------------- */
  var gameList = document.getElementById("gameList");
  if (gameList && GAMES.length) {
    var groups = [
      { key: "playing", label: "Now playing" },
      { key: "finished", label: "Finished" },
      { key: "shelved", label: "Shelved" }
    ];
    gameList.innerHTML = groups.map(function (g) {
      var rows = GAMES.filter(function (x) { return x.status === g.key; });
      if (!rows.length) return "";
      return '<section class="game-group">' +
        '<div class="rubric" role="presentation"><span class="rubric-label">' + g.label +
        (g.key === "playing" ? ' <span class="live-pill"><span class="live-dot" aria-hidden="true"></span>Live</span>' : "") +
        "</span></div>" +
        '<ul class="games">' + rows.map(function (x) {
          return '<li class="game">' +
            '<div class="game-head"><span class="game-title">' + esc(x.title) + "</span>" +
            '<span class="platpill">' + esc(x.platform) + "</span>" +
            '<span class="game-when">' + esc(x.when || "") + "</span></div>" +
            (x.note ? '<p class="game-note">' + esc(x.note) + "</p>" : "") +
            "</li>";
        }).join("") + "</ul></section>";
    }).join("");
  }

  /* ----------------------------------------------------------
     WRITING page
     ---------------------------------------------------------- */
  var writingList = document.getElementById("writingList");
  if (writingList && WRITING.length) {
    writingList.innerHTML = WRITING.map(function (w) {
      return '<article class="piece" id="' + esc(w.slug) + '">' +
        '<span class="kicker">' + esc(w.when) + "</span>" +
        "<h2>" + esc(w.title) + "</h2>" +
        (w.deck ? '<p class="piece-deck">' + esc(w.deck) + "</p>" : "") +
        (w.paragraphs || []).map(function (p) { return '<p class="piece-body">' + p + "</p>"; }).join("") +
        "</article>";
    }).join("");
  }
})();
