/* ============================================================
   CODY HEART — behavior. No animation libraries: the entrance
   choreography is CSS (see MOTION HELPERS in review.css), so
   content is never gated on a script loading or a timeline
   ticking. This file only wires up chrome — nav, dropdowns,
   mobile menu, the theme control — plus one enhancement: the
   dashboard stat count-up.

   The chrome MARKUP is not here. It is generated by
   scripts/shell.js and swept into every page; this file only
   gives it behavior.
   ============================================================ */
(function () {
  "use strict";

  document.documentElement.classList.remove("no-js");
  document.documentElement.classList.add("js");

  var reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;

  /* ----------------------------------------------------------
     Nav: hide on scroll down / show on scroll up, dropdowns
     that open on hover or click and close on Esc / outside
     click / scroll, and the full-screen mobile menu.
     ---------------------------------------------------------- */
  function setupNav() {
    setupTheme();

    /* The bar stays put now — hiding it on scroll meant animating a
       transform on a blurred sticky element, which flickered over
       the photo wall. All that's left is the page name fading in
       once you're past the masthead. */
    var nav = document.querySelector(".nav");
    if (nav) {
      var title = nav.querySelector(".nav__scrolltitle");
      if (title) {
        /* It is a <button>, so while it sits at opacity 0 waiting to be
           scrolled into view it still takes a tab stop — the first one
           on every page, landing on nothing a sighted keyboard user can
           see. Take it out of the order until it is actually shown. */
        var showTitle = function () {
          var on = window.scrollY > 200;
          title.classList.toggle("is-visible", on);
          title.tabIndex = on ? 0 : -1;
        };
        showTitle();
        window.addEventListener("scroll", showTitle, { passive: true });
      }
      if (title) {
        title.addEventListener("click", function () {
          window.scrollTo({ top: 0, behavior: reduced ? "auto" : "smooth" });
        });
      }
    }

    /* Dropdowns (Collections, Elsewhere) */
    Array.prototype.forEach.call(document.querySelectorAll(".nav__drop"), function (drop) {
      var btn = drop.querySelector("button");
      var menu = drop.querySelector(".nav__menu");
      if (!btn || !menu) return;
      var closeTimer;

      function open() {
        clearTimeout(closeTimer);
        // Only one dropdown open at a time
        Array.prototype.forEach.call(document.querySelectorAll(".nav__menu.is-open"), function (m) {
          if (m !== menu) {
            m.classList.remove("is-open");
            m.setAttribute("aria-hidden", "true");
            var b = m.parentElement.querySelector("button");
            if (b) b.setAttribute("aria-expanded", "false");
          }
        });
        menu.classList.add("is-open");
        btn.setAttribute("aria-expanded", "true");
        menu.setAttribute("aria-hidden", "false");
      }
      function close() {
        menu.classList.remove("is-open");
        btn.setAttribute("aria-expanded", "false");
        menu.setAttribute("aria-hidden", "true");
      }
      function delayedClose() {
        clearTimeout(closeTimer);
        closeTimer = setTimeout(close, 100);
      }

      btn.addEventListener("click", function () {
        menu.classList.contains("is-open") ? close() : open();
      });
      drop.addEventListener("mouseenter", function () {
        if (window.matchMedia("(hover: hover)").matches) open();
      });
      drop.addEventListener("mouseleave", function () {
        if (window.matchMedia("(hover: hover)").matches) delayedClose();
      });
      document.addEventListener("keydown", function (e) {
        if (e.key === "Escape" && menu.classList.contains("is-open")) { close(); btn.focus(); }
      });
      document.addEventListener("mousedown", function (e) {
        if (menu.classList.contains("is-open") && !drop.contains(e.target)) close();
      });
      window.addEventListener("scroll", function () {
        if (menu.classList.contains("is-open")) close();
      }, { passive: true });
    });

    /* Mobile menu */
    var burger = document.querySelector(".nav__burger");
    var mobile = document.querySelector(".mobile-menu");
    if (burger && mobile) {
      var pinTimer;
      var setMobile = function (openState) {
        mobile.classList.toggle("is-open", openState);
        burger.setAttribute("aria-expanded", String(openState));
        burger.setAttribute("aria-label", openState ? "Close menu" : "Open menu");
        /* html is the scrolling element here, so locking body alone
           leaves the page scrolling behind the open menu */
        document.body.classList.toggle("menu-locked", openState);
        document.documentElement.classList.toggle("menu-locked", openState);
        /* The sheet opens under the bar and leans on it — the wordmark,
           the theme glyph and the cross that shuts it again are all up
           there — so the bar is pinned for as long as the sheet is on
           screen. That is longer than it is locked: unpin on the same
           tick as the unlock and the bar drops back into the scrolled
           page while the sheet is still fading, and the sheet paints
           over the top of it. 200ms is the fade in css/review.css. */
        clearTimeout(pinTimer);
        if (openState) document.documentElement.classList.add("menu-open");
        else pinTimer = setTimeout(function () {
          document.documentElement.classList.remove("menu-open");
        }, 200);
      };
      burger.addEventListener("click", function () {
        setMobile(!mobile.classList.contains("is-open"));
      });
      document.addEventListener("keydown", function (e) {
        if (e.key === "Escape" && mobile.classList.contains("is-open")) { setMobile(false); burger.focus(); }
      });
      mobile.addEventListener("click", function (e) {
        if (e.target.closest("a")) setMobile(false);
      });
    }
  }

  /* ----------------------------------------------------------
     Theme. Three states. "auto" follows the sun — the inline head
     script does that arithmetic before first paint — while "light"
     and "dark" pin it. The bar's glyph cycles auto → light → dark;
     the picker in the mobile menu sets a state directly.

     LIGHT is the default, so light is the state that CLEARS the key
     and auto/dark are the ones written down. Whichever state means
     "nothing stored" has to be the same here as in THEME_INIT over in
     scripts/shell.js, or a fresh tab paints one thing and the picker
     claims another. (It was auto that cleared until the default moved;
     the reason the clearing state exists at all is that the old
     two-way switch wrote storage on its first click and left no way
     back to the default at all.)
     ---------------------------------------------------------- */
  function setupTheme() {
    var root = document.documentElement;
    var ORDER = ["auto", "light", "dark"];
    var SAYS = {
      auto: "Theme: auto, following the sun",
      light: "Theme: light",
      dark: "Theme: dark"
    };

    function current() {
      var v = root.getAttribute("data-theme");
      return ORDER.indexOf(v) === -1 ? "light" : v;
    }

    /* Resolved exactly as the head script resolves it, so cycling
       through auto lands on whatever the sun says at this moment. */
    function sunSaysDark() {
      var t = new Date(), r = Math.PI / 180;
      var y = Math.floor((t - new Date(t.getFullYear(), 0, 0)) / 864e5);
      var q = 23.45 * Math.sin(r * (360 / 365) * (284 + y));
      var c = (Math.cos(90.833 * r) - Math.sin(39 * r) * Math.sin(q * r)) /
        (Math.cos(39 * r) * Math.cos(q * r));
      var H = Math.acos(Math.max(-1, Math.min(1, c))) / r / 15;
      var j = new Date(t.getFullYear(), 0, 1).getTimezoneOffset();
      var n = t.getTimezoneOffset() < j ? 13 : 12;
      var h = t.getHours() + t.getMinutes() / 60;
      return h < n - H || h > n + H;
    }

    function label() {
      var v = current();
      Array.prototype.forEach.call(document.querySelectorAll("[data-theme-cycle]"), function (b) {
        b.setAttribute("aria-label", SAYS[v] + ". Click to change.");
        b.setAttribute("title", SAYS[v]);
      });
      Array.prototype.forEach.call(document.querySelectorAll("[data-theme-set]"), function (b) {
        b.setAttribute("aria-pressed", String(b.getAttribute("data-theme-set") === v));
      });
    }

    var animTimer;
    function set(next) {
      root.setAttribute("data-theme", next);
      try {
        if (next === "light") localStorage.removeItem("hl-theme");
        else localStorage.setItem("hl-theme", next);
      } catch (e) {}
      /* the dissolve is armed per deliberate change, so the theme the
         head script picks before first paint never animates in */
      if (!reduced) {
        root.classList.add("theme-anim");
        clearTimeout(animTimer);
        animTimer = setTimeout(function () { root.classList.remove("theme-anim"); }, 420);
      }
      root.classList.toggle("dark", next === "auto" ? sunSaysDark() : next === "dark");
      label();
    }

    Array.prototype.forEach.call(document.querySelectorAll("[data-theme-cycle]"), function (btn) {
      btn.addEventListener("click", function () {
        set(ORDER[(ORDER.indexOf(current()) + 1) % ORDER.length]);
      });
    });
    Array.prototype.forEach.call(document.querySelectorAll("[data-theme-set]"), function (btn) {
      btn.addEventListener("click", function () { set(btn.getAttribute("data-theme-set")); });
    });

    /* on auto, cross the sunrise/sunset boundary without a reload */
    setInterval(function () {
      if (current() === "auto") root.classList.toggle("dark", sunSaysDark());
    }, 60000);

    label();
  }

  /* ----------------------------------------------------------
     Stat count-up (dashboards). The markup already holds the
     final value, so this is enhancement only: numbers roll up
     when the row scrolls into view, and a hard timer restores
     the exact original text no matter what.
     ---------------------------------------------------------- */
  function setupCountUp() {
    var figures = document.querySelectorAll(".stat .figure[data-count]");
    if (!figures.length || reduced || !("IntersectionObserver" in window)) return;

    function animate(el) {
      if (el.getAttribute("data-counted")) return;
      el.setAttribute("data-counted", "1");
      var finalText = el.textContent;
      var end = parseFloat(el.getAttribute("data-count"));
      if (isNaN(end)) return;
      var pre = el.getAttribute("data-pre") || "";
      var post = el.getAttribute("data-post") || "";
      var dec = (el.getAttribute("data-count").split(".")[1] || "").length;
      var dur = 1200;
      var t0 = performance.now();
      var done = false;
      function finish() {
        if (done) return;
        done = true;
        el.textContent = finalText;
      }
      function tick(now) {
        if (done) return;
        var p = Math.min((now - t0) / dur, 1);
        var eased = 1 - Math.pow(1 - p, 3);
        var v = end * eased;
        el.textContent = pre + (dec ? v.toFixed(dec) : Math.round(v).toLocaleString("en-US")) + post;
        if (p < 1) requestAnimationFrame(tick);
        else finish();
      }
      requestAnimationFrame(tick);
      /* Wall-clock backstop: if rAF is throttled or never runs to
         completion, the exact original figure is put back. */
      setTimeout(finish, dur + 800);
    }

    var io = new IntersectionObserver(function (entries) {
      entries.forEach(function (entry) {
        if (entry.isIntersecting) {
          animate(entry.target);
          io.unobserve(entry.target);
        }
      });
    }, { rootMargin: "0px 0px -10% 0px" });
    Array.prototype.forEach.call(figures, function (el) { io.observe(el); });
  }

  /* ----------------------------------------------------------
     Boot
     ---------------------------------------------------------- */
  function boot() {
    setupNav();
    setupCountUp();
  }
  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
