#!/usr/bin/env python3
"""Sync the site from Goodreads.

Two jobs, both driven by the public RSS feeds of Cody's shelves:

1. Currently reading — rewrites the window.CURRENT block in js/books.js
   from the "currently-reading" shelf.
2. Five-star drafts — any book rated 5 stars on the "read" shelf (finished
   after CUTOFF) that isn't already on the site gets a pre-filled entry
   appended to js/drafts.js, ready to polish and move into js/books.js.
   That file is never loaded by the site, so nothing goes public until
   Cody moves it.

Run by the sync-goodreads GitHub Action on a schedule; safe to run by
hand from anywhere:

    python scripts/sync-goodreads.py
"""
import json
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from datetime import datetime, timezone
from email.utils import parsedate_to_datetime
from pathlib import Path

USER_ID = "164877363"
FEED = "https://www.goodreads.com/review/list_rss/%s?shelf=%s"
ROOT = Path(__file__).resolve().parent.parent
BOOKS_JS = ROOT / "js" / "books.js"
DRAFTS_JS = ROOT / "js" / "drafts.js"

# Only five-stars finished after this date become drafts — older ones
# were already curated onto (or off) the shelf by hand.
CUTOFF = datetime(2026, 7, 29, tzinfo=timezone.utc)

DRAFTS_HEADER = """\
/* ═══ Drafts — five-star reads waiting for their write-up ═══
   Generated by scripts/sync-goodreads.py when you rate a book
   5 stars on Goodreads. This file is NOT loaded by the site —
   nothing here is public until you move it into js/books.js.

   To publish one: fill in section ("Fiction" or "Nonfiction"),
   tag/tagLabel (the filter chip), and short (your take), then
   cut the block and paste it into the BOOKS list in js/books.js
   wherever you want it to appear.

   Don't want a book on the shelf at all? Delete its block AND
   add its title to DRAFT_SKIP below so the sync doesn't draft
   it again. */

window.DRAFT_SKIP = [
];

window.DRAFTS = [
];
"""


def fetch_shelf(shelf, page=1):
    req = urllib.request.Request(
        FEED % (USER_ID, shelf) + "&page=%d" % page,
        headers={"User-Agent": "heartslibrary-sync/1.0 (+https://heartslibrary.com)"},
    )
    with urllib.request.urlopen(req, timeout=30) as r:
        return ET.fromstring(r.read()).findall("./channel/item")


def fetch_shelf_all(shelf):
    """Walk every page of a shelf feed (Goodreads caps pages at 100 items)."""
    items, page = [], 1
    while True:
        batch = fetch_shelf(shelf, page)
        items.extend(batch)
        if len(batch) < 100:
            return items
        page += 1


def tidy_title(title):
    """Keep card titles short: drop ": subtitle" and "(Series, #1)" tails."""
    title = re.sub(r"\s*\([^)]*\)\s*$", "", title.strip())
    return title.split(": ", 1)[0].strip()


def norm(title):
    """Loose key for matching feed titles against site titles."""
    t = tidy_title(title).lower()
    t = t.replace("’", "'").replace("‘", "'")
    t = t.replace("“", '"').replace("”", '"')
    return re.sub(r"\s+", " ", t)


def read_date(item):
    for field in ("user_read_at", "user_date_added"):
        raw = (item.findtext(field) or "").strip()
        if raw:
            try:
                return parsedate_to_datetime(raw)
            except (TypeError, ValueError):
                pass
    return None


def titles_in(path):
    if not path.exists():
        return set()
    src = path.read_text(encoding="utf-8")
    found = set()
    for t in re.findall(r'"title":\s*"((?:[^"\\]|\\.)*)"', src):
        found.add(norm(json.loads('"%s"' % t)))
    if path == DRAFTS_JS:
        m = re.search(r"window\.DRAFT_SKIP\s*=\s*\[([^\]]*)\];", src)
        if m:
            for t in re.findall(r'"((?:[^"\\]|\\.)*)"', m.group(1)):
                found.add(norm(json.loads('"%s"' % t)))
    return found


# ---------- job 1: currently reading ----------

def sync_current():
    books = []
    for item in fetch_shelf("currently-reading"):
        title = tidy_title(item.findtext("title") or "")
        author = (item.findtext("author_name") or "").strip()
        cover = (
            (item.findtext("book_medium_image_url") or "").strip()
            or (item.findtext("book_image_url") or "").strip()
        )
        book_id = (item.findtext("book_id") or "").strip()
        href = "https://www.goodreads.com/book/show/" + book_id if book_id else ""
        if title:
            books.append({"title": title, "author": author, "cover": cover, "href": href})

    if books:
        entries = ",\n".join(
            "  {\n    \"title\": %s,\n    \"author\": %s,\n    \"cover\": %s,\n    \"href\": %s\n  }"
            % (
                json.dumps(b["title"], ensure_ascii=False),
                json.dumps(b["author"], ensure_ascii=False),
                json.dumps(b["cover"], ensure_ascii=False),
                json.dumps(b["href"], ensure_ascii=False),
            )
            for b in books
        )
        block = "window.CURRENT = [\n%s\n];" % entries
    else:
        block = "window.CURRENT = [];"

    src = BOOKS_JS.read_text(encoding="utf-8")
    new, n = re.subn(
        r"window\.CURRENT\s*=\s*\[[^\]]*\];", lambda m: block, src, count=1
    )
    if n != 1:
        sys.exit("Could not find the window.CURRENT block in js/books.js")
    if new == src:
        print("Currently reading: up to date")
    else:
        BOOKS_JS.write_text(new, encoding="utf-8")
        print("Currently reading: " + "; ".join(b["title"] for b in books))


# ---------- job 2: five-star drafts ----------

def draft_entry(item, when):
    title = tidy_title(item.findtext("title") or "")
    author = (item.findtext("author_name") or "").strip()
    cover = (item.findtext("book_large_image_url") or "").strip()
    review = re.sub(r"\s+", " ", (item.findtext("user_review") or "")).strip()
    j = lambda v: json.dumps(v, ensure_ascii=False)
    return (
        "  {\n"
        "    /* rated 5 stars on Goodreads, finished %s —\n"
        "       fill in section/tag/short, then move into js/books.js */\n"
        '    "title": %s,\n'
        '    "author": %s,\n'
        '    "authorHref": "",\n'
        '    "byLabel": "By",\n'
        '    "section": "Fiction or Nonfiction",\n'
        '    "tag": "",\n'
        '    "tagLabel": "",\n'
        '    "cover": %s,\n'
        '    "featured": false,\n'
        '    "short": %s\n'
        "  }" % (when.strftime("%d %b %Y"), j(title), j(author), j(cover), j(review))
    )


def sync_drafts():
    known = titles_in(BOOKS_JS) | titles_in(DRAFTS_JS)
    fresh = []
    for item in fetch_shelf("read"):
        if (item.findtext("user_rating") or "").strip() != "5":
            continue
        when = read_date(item)
        if when is None or when < CUTOFF:
            continue
        title = tidy_title(item.findtext("title") or "")
        if not title or norm(title) in known:
            continue
        known.add(norm(title))
        fresh.append(draft_entry(item, when))

    if not fresh:
        print("Drafts: nothing new")
        return

    src = DRAFTS_JS.read_text(encoding="utf-8") if DRAFTS_JS.exists() else DRAFTS_HEADER
    m = re.search(r"window\.DRAFTS\s*=\s*\[", src)
    if not m:
        sys.exit("Could not find the window.DRAFTS block in js/drafts.js")
    close = src.index("];", m.end())
    body = src[m.end():close].rstrip()
    joined = (body + ",\n" if body.strip() else "\n") + ",\n".join(fresh) + "\n"
    DRAFTS_JS.write_text(src[: m.end()] + joined + src[close:], encoding="utf-8")
    print("Drafts: %d new five-star read(s) added to js/drafts.js" % len(fresh))


# ---------- job 3: the log (every book on the "read" shelf) ----------

def sync_log():
    entries = []
    for item in fetch_shelf_all("read"):
        title = tidy_title(item.findtext("title") or "")
        if not title:
            continue
        when = read_date(item)
        entries.append({
            "title": title,
            "author": (item.findtext("author_name") or "").strip(),
            "rating": int((item.findtext("user_rating") or "0").strip() or 0),
            "date": when.strftime("%Y-%m-%d") if when else "",
        })
    entries.sort(key=lambda e: e["date"], reverse=True)

    lines = ",\n".join(
        "  { \"title\": %s, \"author\": %s, \"rating\": %d, \"date\": %s }"
        % (
            json.dumps(e["title"], ensure_ascii=False),
            json.dumps(e["author"], ensure_ascii=False),
            e["rating"],
            json.dumps(e["date"]),
        )
        for e in entries
    )
    out = (
        "/* Generated by scripts/sync-goodreads.py — the complete Goodreads\n"
        "   \"read\" shelf, newest first. Do not edit by hand; the sync\n"
        "   overwrites this file. Rendered by log.html via js/log-page.js. */\n"
        "window.LOG = [\n%s\n];\n" % lines
    )
    log_js = ROOT / "js" / "log.js"
    if log_js.exists() and log_js.read_text(encoding="utf-8") == out:
        print("Log: up to date")
    else:
        log_js.write_text(out, encoding="utf-8")
        print("Log: %d books written to js/log.js" % len(entries))


if __name__ == "__main__":
    sync_current()
    sync_drafts()
    sync_log()
